### ISSUE TITLE
Bug and solution for webpack 4

### ISSUE THREAD

**Issue by menduz** [dividab/tsconfig-paths-webpack-plugin#14]
It seems like `enhanced-resolve` doesn't come with webpack 4.
Probably add it as a dependency too?

```
module.js:540
    throw err;
    ^

Error: Cannot find module 'enhanced-resolve/lib/getInnerRequest'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/menduz/code/client/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:8:25)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**Comment by jonaskello** [comment]
Which version of the plugin are you using?

**Comment by jonaskello** [comment]
@jbboehr Perhaps you can open an new issue?
