### ISSUE TITLE
TypeError: filesystem.readJson is not a function​​

### ISSUE THREAD

**Issue by AustinMatherne** [dividab/tsconfig-paths-webpack-plugin#24]
I'm trying to use this with wallaby. Any idea why readJson wouldn't be available?

```
​​[Error] TypeError: filesystem.readJson is not a function​​
​​[Error]     at /.../node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:136:20​​
​​[Error]     at findFirstExistingPath (/.../node_modules/tsconfig-paths/lib/match-path-async.js:81:9)​​
​​[Error]     at /.../node_modules/tsconfig-paths/lib/match-path-async.js:77:20​​
​​[Error]     at filesystem.stat (/.../node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:151:17)​​
​​[Error]     at /.../node_modules/graceful-fs/polyfills.js:284:29​​
​​[Error]     at FSReqWrap.oncomplete (fs.js:152:21)​​
```

**Comment by AustinMatherne** [comment]
It's because of [wallaby-webpack](https://github.com/jeffling/wallaby-webpack/blob/master/lib/WallabyInputFileSystem.js)
