### ISSUE TITLE
 DeprecationWarning: Pass resolveContext instead and use createInnerContext

### ISSUE THREAD

**Issue by elderapo** [dividab/tsconfig-paths-webpack-plugin#30]
I am getting this depracation warning 

```bash
(node:4280) DeprecationWarning: Pass resolveContext instead and use createInnerContext
    at matchPath (/hidden/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:118:150)
    at /hidden/node_modules/tsconfig-paths/lib/match-path-async.js:71:24
    at filesystem.stat (/hidden/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:154:13)
    at SyncAsyncFileSystemDecorator.stat (/hidden/node_modules/enhanced-resolve/lib/SyncAsyncFileSystemDecorator.js:14:4)
    at /hidden/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:148:20
    at findFirstExistingPath (/hidden/node_modules/tsconfig-paths/lib/match-path-async.js:65:9)
    at /hidden/node_modules/tsconfig-paths/lib/match-path-async.js:77:20
    at filesystem.stat (/hidden/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:151:17)
    at SyncAsyncFileSystemDecorator.stat (/hidden/node_modules/enhanced-resolve/lib/SyncAsyncFileSystemDecorator.js:12:12)
    at /hidden/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:148:20
    at findFirstExistingPath (/hidden/node_modules/tsconfig-paths/lib/match-path-async.js:65:9)
    at matchFromAbsolutePathsAsync (/hidden/node_modules/tsconfig-paths/lib/match-path-async.js:30:5)
    at /hidden/node_modules/tsconfig-paths/lib/match-path-async.js:14:16
    at Resolver.<anonymous> (/hidden/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:106:9)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/hidden/node_modules/tapable/lib/Tapable.js:256:13)
    at runNormal (/hidden/node_modules/enhanced-resolve/lib/Resolver.js:130:20)
```

It comes from [webpack/enhanced-resolve/lib/createInnerCallback.js](https://github.com/webpack/enhanced-resolve/blob/fd444a75518e49803c20ff1e98234c4e0d2f5bd3/lib/createInnerCallback.js#L47)

NodeJS version: v9.5.0 (tested with 8 and happens too).
tsconfig-paths-webpack-plugin version: `^3.2.0`

**Comment by Vijayan-Murugan-Mvp** [comment]
I've also seen any solution for this??
