### ISSUE TITLE
ENOENT: no such file or directory, lstat 'true'

### ISSUE THREAD

**Issue by coler-j** [dividab/tsconfig-paths-webpack-plugin#54]
When using this with my nextjs webpack setup I get the following error:

`ENOENT: no such file or directory, lstat 'true'`

```
Error: ENOENT: no such file or directory, lstat 'true'
    at Object.lstatSync (fs.js:1007:3)
    at resolveConfigPath (/Users/user/Documents/GitHub/repo/node_modules/tsconfig-paths/lib/tsconfig-loader.js:43:31)
    at loadSyncDefault (/Users/user/Documents/GitHub/repo/node_modules/tsconfig-paths/lib/tsconfig-loader.js:26:22)
    at tsConfigLoader (/Users/user/Documents/GitHub/repo/node_modules/tsconfig-paths/lib/tsconfig-loader.js:20:22)
    at configLoader (/Users/user/Documents/GitHub/repo/node_modules/tsconfig-paths/lib/config-loader.js:29:22)
    at Object.loadConfig (/Users/user/Documents/GitHub/repo/node_modules/tsconfig-paths/lib/config-loader.js:8:12)
    at new TsconfigPathsPlugin (/Users/user/Documents/GitHub/repo/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:20:42)
    at Object.<anonymous> (/Users/user/Documents/GitHub/repo/next.config.js:20:7)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module.m._compile (/Users/user/Documents/GitHub/repo/node_modules/ts-node/src/index.ts:858:23)

```

**Comment by coler-j** [comment]
The incoming filename in `tsconfig-loader` is the value "true" .... instead of a file name.

![image](https://user-images.githubusercontent.com/7839615/98065393-868c6000-1e22-11eb-81d5-e71de739f42a.png)

**Comment by coler-j** [comment]
Seems to be some interaction with `TS_NODE_PROJECT` property
