### ISSUE TITLE
Module not found: Can't resolve '@/types' in 'my-project/sub/dir'

### ISSUE THREAD

**Issue by silviubogan** [dividab/tsconfig-paths-webpack-plugin#78]
I have this issue and I don't know where to ask about it. I think it is relevant to this project.

This is my `tsconfig.json` file:

```json
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {}
}
```

This is my `tsconfig.base.json` file:

```json
{
  "compilerOptions": {
    "target": "ES6",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strictNullChecks": true,
    "skipLibCheck": true,
    "preserveConstEnums": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "include": ["src"]
}
```

I use CRA (react-scripts) which modifies my `tsconfig.json` file (when starting `npm start`) to remove `baseUrl` and `paths` options from it, so this is why I use `tsconfig.base.json`: to avoid the modification.

I use the following dependencies, although I can change the WebPack version to any version because I don't use the WebPack configuration file for anything. I do not understand what WebPack version is the best from the README.md of this project which states *NOTE: If you are using webpack 4 you need to use version >= 3.0.0 (which is aso backwards compatible with webpack 3).*. Further below I install WebPack 5 and get some other sort of error.

```
tsconfig-paths-webpack-plugin@3.5.1
webpack-cli@3.3.11
typescript@4.3.2
```

The issue is this message:

> Module not found: Can't resolve '@/types' in 'my-project/sub/dir'

1. `@/` is an alias for `./src`
2. the `src/types` directory exists
3. the error occurs only when importing an `enum`
4. the `enum` exported from `@/types` is this:
```ts
export enum PersonType {
  PJ,
  PF,
}
```

This error shows up only on `enum` export. I removed all my `config.webpack.js` file contents and put in it these lines:

```js
const TsconfigPathsPlugin = require("tsconfig-paths-webpack-plugin");

module.exports = {
  resolve: {
    plugins: [
      new TsconfigPathsPlugin({
        extensions: [".js", ".jsx", ".ts", ".tsx"],
      }),
    ],
  },
};
```

But the same error occurs.

If I upgrade to `"webpack": "5.38.1"` and `"webpack-cli": "4.7.2"` then I get this error when running `npm start`:

```log
Starting the development server...

/path/to/my-project/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

TypeError: Cannot read property 'tap' of undefined
    at /path/to/my-project/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:236:65
    at SyncHook.eval [as call] (eval at create (/path/to/my-project/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:13:1)
    at SyncHook.lazyCompileHook (/path/to/my-project/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/path/to/my-project/node_modules/react-scripts/node_modules/webpack/lib/Compiler.js:631:26)
    at /path/to/my-project/node_modules/react-scripts/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/path/to/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at AsyncSeriesHook.lazyCompileHook (/path/to/my-project/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/path/to/my-project/node_modules/react-scripts/node_modules/webpack/lib/Compiler.js:662:28)
    at /path/to/my-project/node_modules/react-scripts/node_modules/webpack/lib/Watching.js:77:18
    at _next1 (eval at create (/path/to/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:1)
```

The `package.json` is this:

```json
{
  "name": "my-project",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@date-io/core": "^1.3.13",
    "@date-io/date-fns": "^1.3.13",
    "@formatjs/intl-pluralrules": "1.3.5",
    "@fortawesome/fontawesome-free": "5.13.0",
    "@hookform/resolvers": "^2.5.1",
    "@manaflair/redux-batch": "1.0.0",
    "@material-ui/core": "^4.11.4",
    "@material-ui/data-grid": "^4.0.0-alpha.30",
    "@material-ui/icons": "4.9.1",
    "@material-ui/lab": "4.0.0-alpha.53",
    "@material-ui/pickers": "^3.3.10",
    "@reduxjs/toolkit": "1.3.6",
    "@tanem/svg-injector": "8.0.50",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.2.7",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.20.13",
    "@types/react": "^17.0.8",
    "@types/react-dom": "^17.0.5",
    "@types/yup": "^0.29.11",
    "apexcharts": "3.19.2",
    "axios": "0.19.2",
    "axios-mock-adapter": "1.18.1",
    "bootstrap": "4.6.0",
    "classnames": "^2.3.1",
    "clipboard-copy": "3.1.0",
    "clsx": "1.1.0",
    "cp-cli": "2.0.0",
    "css-mediaquery": "0.1.2",
    "date-fns": "2.8.1",
    "downshift": "3.4.2",
    "faker": "^5.5.3",
    "fg-loadcss": "2.1.0",
    "formik": "^2.2.8",
    "gravatar": "^1.8.1",
    "json2mq": "0.2.0",
    "jss-rtl": "^0.3.0",
    "lodash": "^4.17.21",
    "material-ui-popup-state": "1.4.1",
    "node-sass": "^4.0.0",
    "object-path": "0.11.4",
    "perfect-scrollbar": "1.5.0",
    "prop-types": "15.7.2",
    "react": "16.14.0",
    "react-bootstrap": "1.0.1",
    "react-bootstrap-table-next": "4.0.2",
    "react-bootstrap-table2-paginator": "2.1.2",
    "react-clock": "^3.0.0",
    "react-datepicker": "2.16.0",
    "react-dom": "16.12.0",
    "react-draggable": "4.4.2",
    "react-dropzone-uploader": "^2.11.0",
    "react-hook-form": "^7.6.10",
    "react-inlinesvg": "1.2.0",
    "react-intl": "3.6.2",
    "react-is": "16.13.1",
    "react-numeric-input": "^2.2.3",
    "react-perfect-scrollbar": "1.5.8",
    "react-portal": "4.2.0",
    "react-redux": "7.1.3",
    "react-router-dom": "5.1.2",
    "react-scripts": "^4.0.3",
    "react-select": "3.1.0",
    "react-select-virtualized": "^3.0.0",
    "react-swipeable-views": "0.13.9",
    "react-syntax-highlighter": "12.2.1",
    "react-vertical-timeline-component": "^3.3.3",
    "react-virtualized": "^9.22.3",
    "react-window": "1.8.5",
    "redux": "4.0.5",
    "redux-persist": "6.0.0",
    "redux-saga": "1.1.3",
    "socicon": "3.0.5",
    "styled-components": "^5.3.0",
    "tiny-slider-react": "^0.5.3",
    "typescript": "^4.3.2",
    "web-vitals": "^1.0.1",
    "yup": "^0.32.9"
  },
  "scripts": {
    "start": "BROWSER=chromium react-scripts start -o",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "lint": "eslint src",
    "format": "prettier --write \"src/**/*.{js,css,scss,html}\"",
    "rtl": "webpack"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version"
    ]
  },
  "devDependencies": {
    "@types/faker": "^5.5.5",
    "@types/gravatar": "^1.8.1",
    "@types/object-path": "^0.11.0",
    "@types/react-bootstrap-table-next": "^4.0.13",
    "@types/react-clock": "^3.0.0",
    "@types/react-datepicker": "^3.1.8",
    "@types/react-is": "^17.0.0",
    "@types/react-numeric-input": "^2.2.3",
    "@types/react-redux": "^7.1.16",
    "@types/react-router-dom": "^5.1.7",
    "@types/react-select": "^4.0.15",
    "@types/react-vertical-timeline-component": "^3.0.0",
    "@types/styled-components": "^5.1.9",
    "@types/tiny-slider-react": "^0.3.2",
    "@types/uuid": "^8.3.0",
    "copyfiles": "2.1.1",
    "prettier": "1.19.1",
    "sass": "1.32.8",
    "serve": "11.2.0",
    "tsconfig-paths-webpack-plugin": "^3.5.1",
    "webpack": "5.38.1",
    "webpack-cli": "4.7.2",
    "webpack-messages": "2.0.4",
    "webpack-rtl-plugin": "2.0.0"
  }
}
```

(sorry for the ugly package.json, some deps should be put under devDependencies, but I think that I'll do that later)

If I posted this in the wrong place, please direct me to a better place to post this question there.

Please help.

Thanks!

**Comment by silviubogan** [comment]
I reached this place from https://stackoverflow.com/questions/63942578/export-enum-from-user-defined-typescript-path-result-in-module-not-found which is the exact same issue but the way it solves the issue is a bit of a hack. I don't thing it will work for me, using VS Code.

**Comment by silviubogan** [comment]
After reverting to a version of the project that works I can see that importing the enum through an intermediate TS file which writes `export type` I get this error:

> 'MyFluffyEnum' cannot be used as a value because it was exported using 'export type'

It makes a little sense to me, but how can I export an enum then? If I put a separate `export { MyFluffyEnum };` in the intermediate TS file, `@/types/index.tsx`, it still throws the same error: `Module not found: Can't resolve '@/types' in etc.`

Please help! Thanks!

**Comment by silviubogan** [comment]
Solved as in [this SO answer](https://stackoverflow.com/questions/67949873/why-does-vs-code-consider-an-import-valid-but-webpack-does-not/67954253#67954253). Thanks for making this WebPack plugin!
